### ISSUE TITLE
Cannot find main entrypoint CS5001

### ISSUE THREAD

**Issue by bhelx** [extism/dotnet-pdk#11]
```
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [/Users/ben/dylibso/hello-from/hello-from-csharp/HelloFromCsharp.csproj]
```

Tried to compile a pure library and kept getting this error. I thought setting `<OutputType/>` to `Library` might resolve but it did not. What i ended up doing as adding a fake instruction on the top of the file to get the compiler to generate a main, which i then don't use: https://github.com/extism/hello-from/blob/main/hello-from-csharp/Program.cs#L5

**Comment by mhmd-azeez** [comment]
Yeah, unfortunately I haven't been able to find a workaround for that. It seems like a `Main` method is mandatory

**Comment by bhelx** [comment]
No problem, perhaps we just document it then? And maybe we can come up with some kind of convention. Perhaps something like this:

```csharp
using Extism;
// ...

// Note: this is needed to ensure that we export a main but the main is not used so it throws an exception
throw new NotImplementedException("a main export is needed but not supported");

namespace Functions
{
    public class Functions
    {
      // ...
    }
}
```

Or maybe what needs to be there should be more inert? Does the runtime call execute it when loading the plug-in?

I'll go with whatever you decide is best.
