### ISSUE TITLE
The project where import/export functions should be not matter

### ISSUE THREAD

**Issue by furesoft** [extism/dotnet-pdk#15]
It is not good to only allow import/export functions in the plugin. If you change the api of a function you have to change the imports of any plugin instead allow define it in referencing projects to make the usage better. 

For example:
 - A project text.sdk containing all the import definitions and helper methods
 - A plugin referencing test.sdk and use the declared functions
 - The host executing the plugin

**Comment by mhmd-azeez** [comment]
This is fixed by #23

**Comment by mhmd-azeez** [comment]
@furesoft let me know if your use case is not solved yet
