### ISSUE TITLE
Returning byte array from plugin function

### ISSUE THREAD

**Issue by ur-fault** [extism/dotnet-pdk#73]
Hi, I need to return byte buffer from the function, it doesn't matter whether it's allocated by extism or my plugin.

<img width="691" alt="image" src="https://github.com/extism/dotnet-pdk/assets/42314964/3c9f2da6-755c-4656-b1f9-898d30b51782">

When I tried just to return `byte[]`, it responded with error above.

**Comment by ur-fault** [comment]
I'm very sorry, I misunderstood how return values work.

**Comment by mhmd-azeez** [comment]
No worries :) feel free to let us know if you have any questions
